package com.entidades;

public enum NombreCurso {
	PRIMERO_DAW,
	SEGUNDO_DAW,
	PRIMERO_DAM,
	SEGUNDO_DAM,
	PRIMERO_COMERCIO,
	SEGUNDO_COMERCIO,
	PRIMERO_MARKETING,
	SEGUNDO_MARKETING,
	PRIMERO_COCINA,
	SEGUNDO_COCINA
}
